version: "3"

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: localMySQL
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=ch10_xorm
      - MYSQL_USER=root
      - MYSQL_ROOT_HOST=%